### ISSUE TITLE
etcd backup

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#126]
An option to automatically backup ectd e.g. to S3 would be very handy to have.
And an easy restore of course :-)

**Comment by chuckbutler** [comment]
@rimusz I can add a snapshot/dump action to the etcd charm.  I dont think natively binding this to s3 is a good option as we're targeting being cloud agnostic. You could from there, do what you will with the exported data.

Would that be good enough?

**Comment by rimusz** [comment]
sure, that would work, and be cloud agnostic too

**Comment by marcoceppi** [comment]
There's been talk about how to stream backups to $CLOUD in juju. One of the solutions is to have a secondary charm that's like s3-sync, gce-sync, swift-sync, etc. Charms just need to provide a backup interface that describes the file path(s) to backup, each of these cloud specific charms are built on top a base sync layer that has configuration for frequency and actions for restoring and listing backups, etc.

The start, having code path in an action that dumps/restores is a good start.

**Comment by rimusz** [comment]
@marcoceppi sounds as a good solution via `syncs`

**Comment by chuckbutler** [comment]
@rimusz I've released an edge channel build of the etcd charm with the new snapshot/restore actions. The process is documented in the readme, which is displayed on the charm overview.

https://jujucharms.com/etcd/16

You can also deploy this straight away:

```
juju deploy etcd --channel=edge
```

I've tested this on a 3 node scale cluster, snapshot on a single unit, clone/restore, and scale. The process worked well in testing. I'm curious if your findings will be the same. Let me know if you find any issues, otherwise this experimental feature will ship with the next release.

Thanks for filing the bug and kicking this off.

**Comment by rimusz** [comment]
nice, will give it a try

**Comment by rimusz** [comment]
@chuckbutler followed the backup/restore instructions, all good there.
👍

**Comment by chuckbutler** [comment]
Closing as complete, this exists in the edge channel today and will make its way into stable soon.
