### ISSUE TITLE
Need to integrate better in the testgrid

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-canonical-kubernetes#147]
We are on the grid: https://k8s-testgrid.appspot.com/ but clicking our button reveals no results. Other buttons such as "google-aws" have a spread sheet of red and green like this: https://k8s-testgrid.appspot.com/google-aws

Our gubernator results https://k8s-gubernator.appspot.com/builds/canonical-kubernetes-tests/logs/kubernetes-aws-e2e-node also do not show up on the Gubernator home page https://k8s-gubernator.appspot.com/

**Comment by chuckbutler** [comment]
change the dir format to mmddHHMMSS000 instead of mmdd_HH:MM:SS.000

Looks like right now we filter down to subdirs of gs://canonical-kubernetes-tests/logs/kubernetes-gce-e2e-node that match \d+ (so that we can cast them to int, so that we can sort them correctly). Will look into easing this restriction but it is probably more involved than your changing the dir format if that's an option.

**Comment by mbruzek** [comment]
@chuckbutler Do we need the 000 at the end? It looks like we always add that to the timestamp. I could remove that if not needed.

**Comment by chuckbutler** [comment]
I dont think we can remove it, as that was called out by fejta in their instructions on how ot fix our integration
