### ISSUE TITLE
use docker version 1.12.4

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-canonical-kubernetes#182]
docker below version 1.12.4 suffers from deadlocks a lot, would make a sense to use version 1.12.4 in the bundle

**Comment by chuckbutler** [comment]
At present this requires one of two things to happen:

1) Update the docker in archive from 1.12.1 to 1.12.4
2) Migrate from archive to snap packaged docker, which will be much closer to whats in the upstream docker apt archive.

Until such decision has been made, we're in a time-wait on this particular issue. The third alternative would be to use the docker PPA and install directly from there. This has bitten us in the past (See the 1.11 to 1.12 release cycle bugs) and was deemed not stable enough of a source to build our k8s offering on until the release had been properly vetted. Which is why we reverted to archive.

I'm open to further discussion around how we can deliver an excellent docker experience in our charms, without sacrificing stability.

**Comment by castrojo** [comment]
This is being tracked here: https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1655906

**Comment by chuckbutler** [comment]
quite a few updates since 14 days ago. It's going to be revved to 1.12.6 as the original request was 1.12.4. No additional charm updates will be required against the charm, as this is happening in archive, and the charm installs from archive.

We should see this land soonish (without inflecting too much optimism) but it's certainly moving forward swimmingly.

**Comment by marcoceppi** [comment]
That being said, for existing clusters, there's really no unattended upgrades enabled. When this does land, you'll need to `juju run --application kubernetes-worker "sudo apt update; sudo apt dist-upgrade"` this will install docker and there's a good chance workloads might be affected as a result of this.

In the event you want to make sure no workloads are affected, consider the following:

```
juju run-action kubernetes-worker/0 pause
juju show-action-output --wait $ACTION_UUID
juju run --unit kubernetes-worker/0 "sudo apt update; sudo apt dist-upgrade"
juju run-action kubernetes-worker/0 resume
```

You'll need to repeat this for each unit of worker.

**Comment by chuckbutler** [comment]
100% positive that workloads will be affected. 

+1 to that note and we should additionally tag this for a documentation update with those instructions.

**Comment by chuckbutler** [comment]
Interesting note @marcoceppi 

```
juju show-action-output --wait 99267d59-f3aa-467d-8686-130e90dc47a0
error: no action ID specified
```

**Comment by marcoceppi** [comment]
Try `juju show-action-output --wait -1s <UUID>` seems to be a bug?

**Comment by chuckbutler** [comment]
This doesn't seem to be as valid as it once was and there's been a lot of churn in this area. I see that our archive versions are quite old in xenial.

```
docker.io:
  Installed: (none)
  Candidate: 1.12.6-0ubuntu1~16.04.1
  Version table:
     1.12.6-0ubuntu1~16.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     1.10.3-0ubuntu6 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

However if we were to migrate to the snap package we would be in the new community edition revisions.

```
docker      17.03.1-ce-1  docker-inc      -        The docker app deployment mechanism
```

Which subsequently is only slightly behind what's in the docker inc ppa (which layer-docker supports, and is the foundation for delivering docker in the k8s charms today), and I'm still unclear if they updated to support the newer ce editions. I don't think there's anything for us to do here until upstream adopts the new downstream moby => docker edition changes, as it doesn't look like we're going to get a bump in the archive packaging anytime soon, and the PPA moves too fast to guarantee a stable delivery target.

**Comment by tvansteenburgh** [comment]
Our stance on this is to support and test with whichever version is in the Ubuntu package archive for the current LTS release of Ubuntu. Right now, that's docker-1.13.1 for Ubuntu 16.04.
