### ISSUE TITLE
Refactor READMEs to point to appropriate upstream documentation.

### ISSUE THREAD

**Issue by castrojo** [juju-solutions/bundle-canonical-kubernetes#185]
- [ ] bundle-canonical-kubernetes
- [ ] kubernetes-core
- [ ] kubernetes charm
- [ ] etcd charm
- [ ] easyrsa charm
- [ ] load balancer-nginx

and appropriate charms/layers

**Comment by wwwtyro** [comment]
Is the plan to simply link to the upstream docs, or to import them into the readme for display on the charm store? If the former:

- How are we going to ensure the upstream docs are in sync with what is in the store?
- Where are we going to track our changes to the docs? PRs against upstream?

**Comment by castrojo** [comment]
Marco's initial idea was to continue to generate the READMEs, however use the upstream markdown files as the source of parts, we should probably scope this out a bit.

**Comment by chuckbutler** [comment]
This is going to be problematic, as the upstream markdown docs are full of google tracking and bits right? How are we going to scrub for our README generation?

**Comment by castrojo** [comment]
Everything in the google tags is in { curlies }, perhaps toss out those statements?

**Comment by mbruzek** [comment]
I do not understand the scope of work here. Is this just adding a few links to the 8 readme files? Or is this some kind of engineering effort with scripting and automation here? 

Since we have control over what is in the charm store we can point to google documentation as much as we want. As Rye points out this may be difficult to keep the google/kubernetes docs up-to-date.

**Comment by chuckbutler** [comment]
cc @tvansteenburgh 

I think this ties in with work you're currently doing
