### ISSUE TITLE
Etcd together with workers?

### ISSUE THREAD

**Issue by toonsevrin** [juju-solutions/bundle-canonical-kubernetes#204]
So I haven't been able to give this a shot yet but is it possible to schedule the etcd cluster on the same nodes as the workers to reduce resource consumption?

**Comment by chuckbutler** [comment]
You  can co-locate etcd on the kubernetes-workers @toonsevrin. However, we call this approach "hulk smashing" because it can have some unintended side effects. Such as port collision with a supporting workload on the worker unit wanting to occupy port's 4001, 2380, 2379.

You cant fully isolate etcd in a lxd container on cloud units as there is additional work that needs to happen for the networking segments. However, if you don't plan on launching etcd (or another workload) that wants those ports, and accept the disk i/o bottlenecks that will happen with having your data/wal directory on the same disk as your containers, there's absolutely nothing stopping you from piloting this and giving it a go.

when you deploy etcd, you'll need to specify to which units with a `to:` directive in the bundle, or if deploying by hand with a `--to` on the command

**Comment by toonsevrin** [comment]
Thanks for answering the question, we map all our ports by dns so I don't see us using anything sub 30000. Would these disk i/o bottlenecks be substantial on a relatively small cluster (<50 low traffic applications, 3 nodes, master is tainted)? We are considering running our production cluster on OVH.com vps's.

**Comment by toonsevrin** [comment]
(Sorry if this is to unrelated to the project)

**Comment by chuckbutler** [comment]
To be completely honest: I haven't done enough performance profiling to make a definitive call. But my *guess* is that it would be fine. If you're only operating a small cluster it should be fine to colocate the applications and get that density out of your deployment. There will be a scale limitation here though, as etcd is the primary bottleneck of a cluster operating with high worker count and busy operations (When you start talking deployments/operations per second).

If you're willing to pilot this and feedback any performance issues, it would be good to have those documented and we can triage appropriately.

Thanks for following up @toonsevrin 👍

**Comment by toonsevrin** [comment]
I'm currently still playing with single node kubernetes, but once I get a complete grasp of things I'll setup a three node testing cluster for our project, and document how it went :)

**Comment by chuckbutler** [comment]
With several days having passed without additional feedback I presume this issue has been resolved. I'm going to close this for now. if any further issues should arise regarding having etcd colocated with the workers feel free to re-open.
