### ISSUE TITLE
Correct misleading documentation for deployment in kubernetes-core bundle fragment.

### ISSUE THREAD

**Issue by zacbayhan** [juju-solutions/bundle-canonical-kubernetes#206]
Sorry if this is a mistake on my end and not actually an issue with the program. using the following guide (https://jujucharms.com/kubernetes-core/) I get the the command to deploy kubernetes (juju deploy canonical-kubernetes ) and then I get the easy rsa error
(ERROR cannot deploy bundle: cannot upgrade application "easyrsa": bundle charm "cs:~containers/easyrsa-6" is incompatible with existing charm "cs:~containers/xenial/easyrsa-6") 

I'm not sure whats going on

**Comment by chuckbutler** [comment]
Greetings @zacbayhan 

First: I'm extremely sorry you encountered this. It looks like our last bundle push has some artifacts that we didn't catch during our QA process where you're attempting to deploy canonical Kubernetes over a lighter weight distribution of our Kubernetes product.

Kubernetes-Core is intended to be the minimal bundle to deploy Kubernetes and "kick the tires" on local systems or in the cloud, using only 3 machines where the Canonical Distribution of Kubernetes requires 9 units out of the box and is intended more for pre-prod/production usage. Or at a minimum, a jumping off point to your deployment for those environments.

What's actually happening there, is it's attempting to switch from a series-versioned charm to a non-series-versioned URL, and it's complaining because the meta of that charm URL (or something very near to that) is causing it to err in favor of preserving the state of the existing deployment. 

You would find a similar error if you attempted to deploy say, a centos-6 or trusty charm over a Xenial charm. 

This is not a critical error, and we will take some care to clean that verbiage up on our next push of the bundle(s).  Thank you for reporting this!

**Comment by minh5** [comment]
@chuckbutler what would be the best way to skirt this problem in the meantime? I'm getting the same error

**Comment by chuckbutler** [comment]
@minh5 When you run conjure-up canonical-kubernetes it should create a new model and deploy the correct bundle into that model.

The documentation here was not clear that you're deploying the same app in different configurations. Kubernetes-core is intended to be lightweight and give you the capability of running a modeled Kubernetes cluster (with minimal system requirements) on your laptop, like in LXD or in very tight budgets on the cloud. The canonical kubernetes is deploying the same application, but scaled out for beginner usage in bare minimum production recommended settings (minus hardware constraints), where all you need to go from there is juju add-unit on your individual applications you wish to scale.

So the skirt problem is to just avoid attempting to juju deploy kubernetes, and instead use conjure-up as your go-to source of deploying kubernetes. It always assumes a fresh model unless configured otherwise.

If you're done exploring with kubernetes-core and ready to upgrade to canonical-kubernetes, its one command

`conjure-up canonical-kubernetes`

The juju deploy command assumes you have not deployed the application.

**Comment by gsf** [comment]
I found this issue because the Usage section for kubernetes-core is the same as the Usage for canonical-kubernetes, saying `conjure up canonical-kubernetes`. I'm assuming it should instead read `conjure up kubernetes-core` in that command block and drop the "This bundle is for multi-node deployments..." paragraph. Is that correct?

**Comment by tvansteenburgh** [comment]
@gsf Yes, you are correct, thanks for pointing that out!
