### ISSUE TITLE
canonical-kubernetes bundle suppport master HA mode?

### ISSUE THREAD

**Issue by meihui** [juju-solutions/bundle-canonical-kubernetes#366]
Hi There,

I am trying to use juju (canonical-kubernetes bundle) to setup kubernetes. It works well with simple master.Is there steps to make the master HA? I just change the unit# in the bundle and re-deploy it but seems both master stop at following stage.

-------Waiting for kube-system pods to start----------
Your help will be highly appreciated.
Thanks, Eric 
 ps

I have tried to update the controller and scheduler services and add `--leader-elect` as arg by following (and restart the schedule/controller). Seems not working.
`sudo vi /var/snap/kube-controller-manager/68/args`

**Comment by ktsakalozos** [comment]
Hi @meihui 

Deploying a bundle with multiple masters should have no problems. Did test one such bundle just now http://paste.ubuntu.com/25182427/ and got to this state http://paste.ubuntu.com/25182432/ .

I am very curious to see why services did not start on your deployment. "Waiting for kube-system pods to start" comes towards the end of the deployment, I assume you gave it enough time... so... I would need to ask you for the syslogs of the masters and workers to see what went wrong. Also where did you deploy this multi master bundle? My test was on AWS.

Let me clarify the HA you get right now. At this point the master HA offered is handled by Juju and not by each Kubernetes service separately. If you deploy multiple masters one of the masters will be elected as a leader. The leader unit is marked with a * on the juju status. If you remove the master another master will take over leadership. This approach does not make use of the --leader* options of the kubernetes services. As a result you might need to wait a couple of minutes before a new master takes over. We also do not ship CDK with multiple masters by default because further testing is needed.

**Comment by tvansteenburgh** [comment]
1. Note that if you already have a canonical-kubernetes deployed, you can add another master with: `juju add-unit kubernetes-master`.
2. If the deployment stays in the status you mentioned and never becomes ready, you can collect debug info by running the script in this repo: https://github.com/juju-solutions/cdk-field-agent. Attach the resulting tarball here and we can help debug. Thanks!

**Comment by meihui** [comment]
Thanks @ktsakalozos  and @tvansteenburgh for the quick response. Highly appreciated. 

Please check the cdk collect tool output here.

[results-2017-07-27-13-13-33.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/1180047/results-2017-07-27-13-13-33.tar.gz)

**Comment by meihui** [comment]
@tvansteenburgh Thanks for the hint too. add-unit was the first thing I did to my single-master cluster. resulting in the same result. Then I thought there might be race condition issue so I restart the deployment and only find out it reach the same stage.

My deployment is using the juju/manual with VMs (from on openstack lab). Following following steps:
b

1. Built openstack with 12 machines, 16.04.
2. one VM built as the juju workstation.
3. one VM bootstraped as the controllor
4. juju added 10 nodes as manual/ssh machines.
5. 10 nodes to built as kubernetes cluster (2 masters and 3 workers).

**Comment by Cynerva** [comment]
@meihui I haven't looked at this in much detail yet, but here are a couple of early observations from the data you posted.

---

All pods are stuck in a pending state, with only a single event:
```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  10h		42s		634	kubelet, 2ndkube-10			Warning		FailedSync	Error syncing pod
```

Nothing much helpful, here.

---

On kubernetes-master/1, the kube-scheduler service is not running:
```
● snap.kube-scheduler.daemon.service - Service for snap application kube-scheduler.daemon
   Loaded: loaded (/etc/systemd/system/snap.kube-scheduler.daemon.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2017-07-27 02:52:05 UTC; 10h ago
  Process: 4319 ExecStart=/usr/bin/snap run kube-scheduler.daemon (code=exited, status=2)
 Main PID: 4319 (code=exited, status=2)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

Since the journal has rotated, it's not clear why it's inactive. You can try restarting it with this command:
```
juju run --unit kubernetes-master/1 'service snap.kube-scheduler.daemon restart'
```

---

On kubernetes-master/1, I see a gopanic followed by this in the kube-apiserver logs:
```
Get https://2ndkube-6:10250/containerLogs/default/nginx-ingress-controller-lrnrf/nginx-ingress-lb: dial tcp: lookup 2ndkube-6 on 138.120.252.54:53: no such host
```

This failed DNS lookup is probably not the source of your problem, but may lead to other issues later on. In particular, `kubectl logs` and `kubectl exec` might fail for you. See [this issue](https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/171) for more info.

---

On kubernetes-worker/0, I see errors coming from kubelet:
```
Jul 27 13:11:48 2ndkube-10 snap[18187]: E0727 13:11:48.414347   18187 remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = unable to pull sandbox image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp 74.125.21.82:443: i/o timeout"}
Jul 27 13:11:48 2ndkube-10 snap[18187]: E0727 13:11:48.414406   18187 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "nginx-ingress-controller-swq9g_default(aa8d9757-7245-11e7-a042-fa163edbb2f6)" failed: rpc error: code = 2 desc = unable to pull sandbox image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp 74.125.21.82:443: i/o timeout"}
Jul 27 13:11:48 2ndkube-10 snap[18187]: E0727 13:11:48.414439   18187 kuberuntime_manager.go:618] createPodSandbox for pod "nginx-ingress-controller-swq9g_default(aa8d9757-7245-11e7-a042-fa163edbb2f6)" failed: rpc error: code = 2 desc = unable to pull sandbox image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp 74.125.21.82:443: i/o timeout"}
Jul 27 13:11:48 2ndkube-10 snap[18187]: E0727 13:11:48.414486   18187 pod_workers.go:182] Error syncing pod aa8d9757-7245-11e7-a042-fa163edbb2f6 ("nginx-ingress-controller-swq9g_default(aa8d9757-7245-11e7-a042-fa163edbb2f6)"), skipping: failed to "CreatePodSandbox" for "nginx-ingress-controller-swq9g_default(aa8d9757-7245-11e7-a042-fa163edbb2f6)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-ingress-controller-swq9g_default(aa8d9757-7245-11e7-a042-fa163edbb2f6)\" failed: rpc error: code = 2 desc = unable to pull sandbox image \"gcr.io/google_containers/pause-amd64:3.0\": Error response from daemon: {\"message\":\"Get https://gcr.io/v1/_ping: dial tcp 74.125.21.82:443: i/o timeout\"}"
```

This bit here:
```
https://gcr.io/v1/_ping: dial tcp 74.125.21.82:443: i/o timeout
```

is probably why the pods are stuck in a pending state. Kubelet is not able to pull the docker images it needs from gcr.io. It's unclear to me why this is happening, though.

**Comment by meihui** [comment]
@Cynerva Thanks a lot for the investigation.  I will rerun the scenario. There might be proxy issue during this time frame. That might echo the symptom (access to gcr.io timeout) here. Will update more.

Again thanks for the prompt response and support!

**Comment by meihui** [comment]
feedback (sorry for the delay. just finished 2-week vacation).

It is working after I remove the extra/erroneous setting on no_proxy. (Bring owls to Athens).

ie, "juju config kubernetes-worker  http_proxy=http://myproxy:myport https_proxy=http://myproxy:myport" is sufficient. add no_proxy will be troublesome.

Thanks for all the excellent support.
