### ISSUE TITLE
Installing from outdated docker apt respository

### ISSUE THREAD

**Issue by drewboswell** [juju-solutions/bundle-canonical-kubernetes#388]
When provisioning a kubernetes worker via juju, docker is installed as a dependency (from what I can tell).

Docker is installed via the old method and we are therefor stuck with a version of docker that dates back to january. Please update the dependency to follow the guidelines here:

https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

Thanks,

Andrew,

**Comment by tvansteenburgh** [comment]
Kubernetes officially supports up through Docker 1.12.6, which is what we install from the Ubuntu (Xenial) main archive. This will probably increase to 1.13.x in the near future. If you want more recent than that you are welcome to update the nodes (at your own risk), but it's unlikely that we would ever install a more recent Docker version than what Kubernetes itself supports.

**Comment by drewboswell** [comment]
Alright, good to know. Is this documented anywhere? I can't seem to find any reference to what version is installed, and how it is done (which charm brings it in as a dependency).

I also don't see any doc for how to integrate the docker-ee vs docker-ce depending on whether you have paid for the licenses. Is this available somewhere?

**Comment by catesandrew** [comment]
Two issues show that Docker is supported up to 17.0x. They are located [here](https://github.com/kubernetes/kubernetes/pull/52666) and [here](https://github.com/kubernetes/kubernetes/issues/42926).

I am in need of updating docker to fix "privileged docker failing in lxd container due to /dev/.lxc/proc/" bug. Its discussed on [Moby Issue #32758](https://github.com/moby/moby/issues/32758) and [Moby Issue #32968](https://github.com/moby/moby/issues/32968). I think these are the same issue reported at [Rancher Issue #7968](https://github.com/rancher/rancher/issues/7968), and fixed in RunC here: [runc Issue #1327](https://github.com/opencontainers/runc/pull/1327).

**Comment by tvansteenburgh** [comment]
The new default Docker on Ubuntu 16.04 is 1.13.1. We're testing 17.03.02 now, and it'll be the new default soon (probably shortly after the k8s 1.9 release).

**Comment by tvansteenburgh** [comment]
We now install Docker 18.06 by default, and the charm can be configured to use a different version if desired (see https://github.com/juju-solutions/layer-docker/pull/127).
