### ISSUE TITLE
canonical-kubernetes - pending external IP 

### ISSUE THREAD

**Issue by lghinet** [juju-solutions/bundle-canonical-kubernetes#410]
Hello,

i am using juju canonical-kubernetes, on localhost, 
I ve created a service type: LoadBalancer, but its not getting an IP address, although i have installed a load balancer, using conjure-up and lxd 

thank you

**Comment by tvansteenburgh** [comment]
Hi @lghinet,

LoadBalancer only allocates an IP on cloud providers that support it (like AWS), not localhost. What you probably want is a ClusterIP or NodePort Service type, not LoadBalancer. I would recommend reading https://kubernetes.io/docs/concepts/services-networking/service/ for all the details. especially [this section](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types).

**Comment by lghinet** [comment]
hello
yes you are right, but i was hoping to get an external IP which is in fact an ip from my local network , reachable from my local network, just outside kubernetes cluster 

i setup my service to be NodePort,  and created a simple ingress 

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kafka-ingress
spec:
  backend:
    serviceName: kafka-service-1
    servicePort: 9092
```

i was hoping to access it through the load balancer IP (which has an ip from my local network and it will be reachable to other computers from the same network )
exactly the same way i am accessing the dashboard , through the load balancer ip

**Comment by wwwtyro** [comment]
@lghinet Hopefully this works for you: https://medium.com/@ryeterrell/externally-exposing-a-lxd-based-kubernetes-service-821311461950

**Comment by vasicvuk** [comment]
@wwwtyro  In this way of setup (Link from medium) you have single point of failure. If node that was specified in iptables goes down service will not be available publicly since that ip address is not active. Better way is to setup external load balancer independent of Kubernetes with floating ip address between multiple machines pointing to all kubernetes nodes but still it would be nice for Kubernetes to just get IP address from local network pool and use it as Floating IP.
