### ISSUE TITLE
Deploy of kubernetes can take a long time to achieve active

### ISSUE THREAD

**Issue by fraenkel** [juju-solutions/bundle-canonical-kubernetes#423]
Today we started to notice a wide variance on deploy times to achieve a complete Kubernetes deployment with Canal.
It normally takes 10-15 minutes, but today we noticed times upward of 35 minutes.

Here is an example of what I am seeing:
```
kubernetes-master/0*  waiting   executing   4        161.192.139.180  6443/tcp  Waiting for kube-system pods to start
  canal/0*            active    idle                 161.192.139.180            Flannel subnet 10.1.13.1/24
kubernetes-worker/0*  waiting   executing   5        161.192.139.141            Waiting for cluster DNS.
  canal/1             waiting   allocating           161.192.139.141            agent initializing
kubernetes-worker/1   waiting   executing   6        161.192.139.166            Waiting for kube-proxy to start.
  canal/2             waiting   allocating           161.192.139.166            agent initializing
kubernetes-worker/2   waiting   executing   7        161.192.139.198            Waiting for kube-proxy to start.
  canal/3             waiting   allocating           161.192.139.198            agent initializing
```
then it goes to
```
kubernetes-master/0*  waiting   executing   4        161.192.139.180  6443/tcp  Waiting for kube-system pods to start
  canal/0*            active    idle                 161.192.139.180            Flannel subnet 10.1.13.1/24
kubernetes-worker/0*  waiting   executing   5        161.192.139.141            Waiting for cluster DNS.
  canal/1             waiting   allocating           161.192.139.141            agent initializing
kubernetes-worker/1   blocked   executing   6        161.192.139.166            Missing cni resource.
  canal/2             waiting   allocating           161.192.139.166            agent initializing
kubernetes-worker/2   waiting   executing   7        161.192.139.198            Waiting for kube-proxy to start.
  canal/3             waiting   allocating           161.192.139.198            agent initializing
```

It will cycle around until it starts to work which can take a very "long" time.

**Comment by Cynerva** [comment]
Regarding this: `Missing cni resource.`

Not entirely sure how it happened, but kubernetes-worker-54 no longer has a cni resource associated with it on the charm store. We will be fixing this in a day or so with a new release of canonical-kubernetes-canal.

We don't expect the cni resource to disappear again in future releases; best guess is that this happened because kubernetes-worker-54 never made it to the stable channel of kubernetes-worker. That's an artifact from our release process that won't occur again.

If you need a short-term workaround, I'd suggest the following:
1. download the canonical-kubernetes-canal [bundle.yaml](https://api.jujucharms.com/charmstore/v5/canonical-kubernetes-canal/archive/bundle.yaml)
2. change kubernetes-worker charm from `cs:~containers/kubernetes-worker-54` to `cs:~containers/kubernetes-worker-52` (latest in stable channel)
3. `juju deploy ./bundle.yaml`

Again, we should have a proper fix for this out in a day or so.

> It will cycle around until it starts to work which can take a very "long" time.

Given the missing cni resource, I wouldn't expect the cluster to settle in a working state. Maybe far enough to create pods, but I'd expect them to have network problems at this point.

**Comment by fraenkel** [comment]
Switching to 52 fixed the problem.
