### ISSUE TITLE
how to add `DefaultStorageClass` to `--admission-control`

### ISSUE THREAD

**Issue by sameersbn** [juju-solutions/bundle-canonical-kubernetes#451]
I've been trying to configure dynamic volume provisioning with canonical-kubernetes. For this to work `DefaultStorageClass` needs to be added to param list passed to the `--admission-control` argument. 

I tried specifying the argument `admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultTolerationSeconds,DefaultStorageClass` to the `api-extra-args` configuration of the kubernetes-master deployment (see screenshot), but this did not work and resulted in a broken deployment. 

What is the proper way of adding `DefaultStorageClass` to the `kube-apiserver` command ??

![ss](https://user-images.githubusercontent.com/410147/33673159-0eb242d4-dad2-11e7-87b9-020b6941035d.png)

**Comment by marcoceppi** [comment]
@Cynerva Can you take a look at this?

**Comment by Cynerva** [comment]
> I tried specifying the argument `admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultTolerationSeconds,DefaultStorageClass` to the `api-extra-args` configuration of the kubernetes-master deployment (see screenshot), but this did not work and resulted in a broken deployment.

This is supposed to be the proper way to do it. But... it doesn't work, due to a bug with how `api-extra-args` handles commas.

The `api-extra-args` arguments are added to FlagManager [here](https://github.com/kubernetes/kubernetes/blob/ce90b54c0fa6d48d5c6b375576a8494e82997a11/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L1081), but without setting `strict=True`. As a result, FlagManager does some [unfortunate comma-splitting logic that we don't want](https://github.com/kubernetes/kubernetes/blob/ce90b54c0fa6d48d5c6b375576a8494e82997a11/cluster/juju/layers/kubernetes-master/lib/charms/kubernetes/flagmanager.py#L68).

The good news is, this should be fixed by a recent rework I did that removes FlagManager entirely:
https://github.com/kubernetes/kubernetes/pull/55185
https://github.com/kubernetes/kubernetes/pull/55334

That fix hasn't been released to stable channels yet, and we can't release until sometime after the upstream Kubernetes code freeze ends on Dec 11. I'm hopeful we can get a release out sometime late next week, but we'll see.

@sameersbn for now, the best I can offer is a couple workarounds, though they come with downsides.

---

**Workaround option 1**: Set admission-control directly using `snap set`

Deploy normally, with no `api-extra-args`, then:

```
juju run --application kubernetes-master -- snap set kube-apiserver admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultTolerationSeconds,DefaultStorageClass
juju run --application kubernetes-master -- service snap.kube-apiserver.daemon restart
```
This should _temporarily_ give you the configuration you want, but some cluster operations will revert it back. As long as you don't change kubernetes-master configuration, do a `juju upgrade-charm`, or add/remove `etcd` units, I think the config should stick.

---

**Workaround option 2**: Deploy charms from the edge channels

You can do this by passing the `--channel edge` option to conjure-up. This should give you a kubernetes-master charm where the `api-extra-args` config works properly.

Just be aware that charms on the edge channel change frequently and have not been thoroughly tested. No guarantees of stability.

**Comment by sameersbn** [comment]
@Cynerva thanks for taking a look and offering the workarounds. Considering this is for a tutorial i'm writing for tutorials.ubuntu.com, the second option looks to be the better choice as it will allow me to make minor changes to the `conjure-up` command when this is fixed upstream

**Comment by sameersbn** [comment]
A follow up question: is there a way to only specify `DefaultStorageClass` so that it's added to the default configuration of the bundle instead of having to list everything `Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultTolerationSeconds,DefaultStorageClass`?

**Comment by Cynerva** [comment]
> A follow up question: is there a way to only specify DefaultStorageClass so that it's added to the default configuration of the bundle instead of having to list everything Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultTolerationSeconds,DefaultStorageClass?

Nope.

This might be a compelling reason for us to add a new charm config specifically to handle extra admission controllers like this. Just off the top of my head, something like `extra-admission-control=DefaultStorageClass,^DefaultTolerationSeconds` that lets you both add and remove from the default set. I'll run this by the team, but chances are we won't get to adding a config like this any time soon.

**Comment by sameersbn** [comment]
ok. thanks for looking into it :+1:

**Comment by wwwtyro** [comment]
@Cynerva Can this be closed?

**Comment by sameersbn** [comment]
I think this issue can be closed. Thanks!
