### ISSUE TITLE
juju config kubernetes-worker allow-privileged=true should be set by default

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#579]
Hi all, 

According to this PR, the allow-privileged should now be set to true by default for the k8s worker/kubelet, I'm not sure how this affects the kubeapi-server: 

[https://github.com/kubernetes/kubernetes/pull/63442](https://github.com/kubernetes/kubernetes/pull/63442)

PSP should now be used: [https://kubernetes.io/docs/concepts/policy/pod-security-policy/](https://kubernetes.io/docs/concepts/policy/pod-security-policy/). 

This has been causing issues with Rancher ([https://github.com/rancher/rancher/issues/13612](https://github.com/rancher/rancher/issues/13612)), so it will fix that as well. 

Cheers

**Comment by CalvinHartwell** [comment]
Raised PR here for this: https://github.com/kubernetes/kubernetes/pull/64104

**Comment by CalvinHartwell** [comment]
Waiting for final review for this fix before merge.

**Comment by ktsakalozos** [comment]
@CalvinHartwell , @Cynerva , @hyperbolic2346  I am missing something here.

We say we will allow containers to be privileged by default. This is because pod security will be handled by Pod Security Policy (PSP). Base on https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podsecuritypolicy if we turn on allow-privileged we should also enable the respective admission control, right? Will this have implications on the addons we ship? For 1.10 PSP seems to not be recommended, will it be recommended for 1.11?

**Comment by CalvinHartwell** [comment]
@ktsakalozos if we want to enable this in 1.11 instead, I'm all for it. As long as we match whatever the upstream recommendations are. Thoughts?
