### ISSUE TITLE
kubernetes-master charm is erroring on deploy with 'allow-privileged' set to True

### ISSUE THREAD

**Issue by jeff-hillman** [juju-solutions/bundle-canonical-kubernetes#644]
During a deploy with allow-privileged: true (or True) set in a bundle, the juju deploy command fails with:

---
- upload charm cs:~containers/kubernetes-master-144 for series xenial
18:19:23 DEBUG httpbakery client.go:243 client do GET https://api.jujucharms.com/charmstore/v5/~containers/bionic/kubernetes-master-144/meta/any?include=id&include=supported-series&include=published {
18:19:23 DEBUG httpbakery client.go:245 } -> error <nil>
18:19:23 DEBUG juju.cmd.juju.application bundle.go:447 added charm cs:~containers/kubernetes-master-144
- deploy application kubernetes-master on xenial using cs:~containers/kubernetes-master-144
18:19:23 DEBUG juju.cmd.juju.application bundle.go:1024 resolve "$addCharm-7" from map[string]string{"addCharm-7":"cs:~containers/kubernetes-master-144"}
18:19:23 INFO  juju.cmd.juju.application series_selector.go:113 with the series "xenial" defined by the bundle
18:19:23 DEBUG juju.api monitor.go:35 RPC connection died
ERROR cannot deploy bundle: cannot deploy application "kubernetes-master": option "allow-privileged" expected string, got true
18:19:23 DEBUG cmd supercommand.go:459 error stack: 
option "allow-privileged" expected string, got true
github.com/juju/juju/api/application/client.go:154: 
github.com/juju/juju/cmd/juju/application/deploy.go:171: 
github.com/juju/juju/cmd/juju/application/bundle.go:568: cannot deploy application "kubernetes-master"
github.com/juju/juju/cmd/juju/application/bundle.go:382: 
github.com/juju/juju/cmd/juju/application/bundle.go:122: 
github.com/juju/juju/cmd/juju/application/deploy.go:720: cannot deploy bundle
github.com/juju/juju/cmd/juju/application/deploy.go:1101: 
---

---
bundle section for kubernetes-master
---

  kubernetes-master:
    annotations:
      gui-x: '800'
      gui-y: '850'
    charm: cs:~containers/kubernetes-master-144
    constraints: cores=2 mem=4G root-disk=16G
    num_units: 2
    options:
      channel: 1.11/stable
      allow-privileged: true
      authorization-mode: RBAC,Node,AlwaysAllow
---

running 'juju config kubernetes-master allow-privileged=true' after the deploy command works perfectly fine, and enabled the proper functionality.

**Comment by Cynerva** [comment]
If you change `allow-privileged: true` to `allow-privileged: "true"` in the bundle, I think this should work.

The quotes are needed because the allow-privileged config expects a string value, not a boolean value. The reason it expects a string value is to support a third value besides `true` or `false`, which is `auto` (the default).

When you run `juju config kubernetes-master allow-privileged=true`, Juju is smart enough to recognize that allow-privileged needs a string, so it treats `true` as a string value instead of a boolean. But when deploying from a bundle with `allow-privileged: true`, Juju isn't able to convert it to a string intelligently - you have to do it yourself by adding quotes. Kind of annoying.

**Comment by jeff-hillman** [comment]
That worked, thanks.
