### ISSUE TITLE
Ingress images (and other key system images) should be updated as part of cluster upgrade

### ISSUE THREAD

**Issue by mthaddon** [juju-solutions/bundle-canonical-kubernetes#649]
We recently upgraded a number of k8s clusters to 1.11. However, the process of updating the ingress images seems to be separate. One cluster in use currently has 1.11 but is using quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.12.0

**Comment by Cynerva** [comment]
Looks like it should have deployed 0.16.1.

@mthaddon can you confirm the `nginx-image` config on kubernetes-worker is set to `auto`? If it's not, then you'll have to either set it to `auto` or bump the image yourself.

**Comment by paulgear** [comment]
nginx-image was not set to auto; from memory, it was set to quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.12.0 because on an earlier CDK version we needed to upgrade to 0.12.0 to get a fix which was shipped with that version.  Perhaps this is more a documentation issue - i.e. we need to make sure to set nginx-image back to auto before commencing the upgrade.

**Comment by paulgear** [comment]
@tvansteenburgh @Cynerva In a related issue, when I did change the value of nginx-image to upgrade the image, it did not trigger any change in the charm; should this be logged as an issue here, or against kubernetes itself (since the bug is probably somewhere around https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L876)?

**Comment by Cynerva** [comment]
@paulgear It works best for us if you open a new issue here for anything relating to CDK: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/new

We don't have good visibility into bugs on the Kubernetes repo, so if you open any there, we're likely to miss them.

**Comment by paulgear** [comment]
@tvansteenburgh I've created issue #653 to track this.

**Comment by tvansteenburgh** [comment]
Closing this since a new issue was opened.
