### ISSUE TITLE
Kubernetes dashboard is no-longer showing when running kubectl cluster-info

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#661]
Hi all,

The kubernetes dashboard is no-longer showing when I run the kubectl cluster-info command and I am having trouble accessing it in other ways, perhaps something is wrong with the pod or recent charm changes. 

Cheers,

- Calvin

**Comment by tvansteenburgh** [comment]
@CalvinHartwell You didn't provide any details about your setup. Can you paste your bundle or output of `juju status` or something?

**Comment by CalvinHartwell** [comment]
Hi Tim,

Same bundle as per: [https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/660](https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/660). Either the broken one or none broken bundle in this thread. 

Also: [https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/663](https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/663) looks related. 

Cheers

**Comment by ktsakalozos** [comment]
The dashboard no longer appears in cluster info because we stopped applying the "kubernetes.io/cluster-service=true" label to its service (https://github.com/juju-solutions/cdk-addons/commit/1ffe0d66a6c65a2ed561be6abfcf167eb7208670#diff-ff9fd45b5036390f6c3de1ad87b0cdacL80).

Normally kubernetes-dashboard does not appear in cluster-info but is available as described here: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui

Unless this (kubernetes-dashboard not appearing in cluster-info) is really a problem, we would like to align with upstream and not label kubernetes-dashboard as a "kubernetes.io/cluster-service".

**Comment by CalvinHartwell** [comment]
> The dashboard no longer appears in cluster info because we stopped applying the "kubernetes.io/cluster-service=true" label to its service (juju-solutions/cdk-addons@1ffe0d6#diff-ff9fd45b5036390f6c3de1ad87b0cdacL80).
> 
> Normally kubernetes-dashboard does not appear in cluster-info but is available as described here: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui
> 
> Unless this (kubernetes-dashboard not appearing in cluster-info) is really a problem, we would like to align with upstream and not label kubernetes-dashboard as a "kubernetes.io/cluster-service".

OK - good to know, this change must have been recently, but I used to see this when the dashboard was not working properly.
