### ISSUE TITLE
e2e SchedulerPredicates tests fail

### ISSUE THREAD

**Issue by jogeo** [juju-solutions/bundle-canonical-kubernetes#672]
The following e2e tests fail when run against the CDK bundle. The bundles, e2e log and juju-crashdump are attached, showing the failures and the machine logs from the deployment.

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if matching  [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:89

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates resource limits of pods that are allowed to run  [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:89

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if not matching  [Conformance] 
/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:89

[juju-crashdump-kubernetes-2018-10-16-02.10.27.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2487879/juju-crashdump-kubernetes-2018-10-16-02.10.27.tar.gz)
[2fbe4ec5-2cb0-45a7-8da1-971dfbd52796.log.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2487880/2fbe4ec5-2cb0-45a7-8da1-971dfbd52796.log.tar.gz)
[bundles.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2487914/bundles.tar.gz)

**Comment by Cynerva** [comment]
This is happening because the [Serial] tests are being run while parallelism is set to 25. Serial tests are labeled as such because they can only run when no other tests are running, meaning they will only work with parallelism=1.

When running the kubernetes-e2e test action, you'll need to either skip the Serial tests (which is [the default](https://github.com/juju-solutions/kubernetes/blob/c5fbce21ef9e4e08e54b23fc5224cb4cbd30cb39/cluster/juju/layers/kubernetes-e2e/actions.yaml#L13)) or run them with `parallelism=1`.

Heads up: if you run all the conformance tests with `parallelism=1`, it can take over an hour to complete. Consider running the test action twice: once with `parallelism=25` for non-Serial tests, and once with `parallelism=1` for just the Serial tests.

**Comment by Cynerva** [comment]
Closing, please let us know if this didn't resolve your issue or you need anything else.
