### ISSUE TITLE
cdk deployments on aws get stuck

### ISSUE THREAD

**Issue by iatrou** [juju-solutions/bundle-canonical-kubernetes#706]
Over a sample of a dozen automated deployments on aws, 30% of them get stuck at a stage like the following:
http://paste.ubuntu.com/p/KSJ8yh3gPh/

The minimal repro case is as follows:
```
wget https://api.jujucharms.com/charmstore/v5/canonical-kubernetes/archive/bundle.yaml
sed -ri 's/series: bionic/series: xenial/g' bundle.yaml
sed -ri 's/num_units: ./num_units: 1/g' bundle.yaml
juju add-model cdk
juju deploy ./bundle.yaml
juju deploy cs:~containers/aws-integrator
juju add-relation 'aws-integrator:aws' 'kubernetes-master:aws'
juju add-relation 'aws-integrator:aws' 'kubernetes-worker:aws'
juju trust aws-integrator
```

As a workaround, the errors get resolved by just rebooting the units.

[results-2018-12-09-18-46-44.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2660893/results-2018-12-09-18-46-44.tar.gz)

**Comment by Cynerva** [comment]
This is the same issue as https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/702, which was fixed by https://github.com/juju-solutions/layer-etcd/pull/145, which was released to the stable charm channel on Dec 7.

@iatrou once you start using the latest stable etcd charm (rev 332+), you should no longer see this issue. Please let us know if you do.
