### ISSUE TITLE
Doc Fix - Missing Relationship kubeapi-load-balancer -> vault

### ISSUE THREAD

**Issue by Silvenga** [juju-solutions/bundle-canonical-kubernetes#714]
Regarding the the [docs](https://www.ubuntu.com/kubernetes/docs/using-vault) or the [wiki](https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/CDK-Certificates-and-Trust-Management) as a template for a HA vault deployment, it appears that a relationship is missing on the overlay.

```bash
juju add-relation kubeapi-load-balancer:certificates vault:certificates
```

```yml
- - kubeapi-load-balancer:certificates
  - vault:certificates
```

Without this the load balancer will fail to configure (`reactive/load_balancer.py:123:install_load_balancer`), which will cause `kubernetes-master` units to fail (with `Waiting for 5 kube-system pods to start`) as no nodes will be registered.

If I'm correct, I would love to make a pr.

**Comment by johnsca** [comment]
Very sorry for the delay!  That is correct; it seems that I created the overlay against [kubernetes-core](https://jujucharms.com/kubernetes-core/) rather than CDK and so I missed that relation.

@Silvenga The docs repo is at https://github.com/juju-solutions/kubernetes-docs and a PR would be very much appreciated!

**Comment by Silvenga** [comment]
Closing as resolved by pr 101.
